--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30/10/2015 09:19:04
-- Server version: 5.6.17
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE sgreserva;

--
-- Definition for table disciplina
--
DROP TABLE IF EXISTS disciplina;
CREATE TABLE disciplina (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  codigo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table periodo
--
DROP TABLE IF EXISTS periodo;
CREATE TABLE periodo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_periodo_id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table predio
--
DROP TABLE IF EXISTS predio;
CREATE TABLE predio (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_predio_id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table professor
--
DROP TABLE IF EXISTS professor;
CREATE TABLE professor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_professor_id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table usuario
--
DROP TABLE IF EXISTS usuario;
CREATE TABLE usuario (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  senha VARCHAR(32) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_usuario_id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table sala
--
DROP TABLE IF EXISTS sala;
CREATE TABLE sala (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predio_id INT(11) DEFAULT NULL,
  nome VARCHAR(255) DEFAULT NULL,
  capacidade INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_sala_predio_id FOREIGN KEY (predio_id)
    REFERENCES predio(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table reserva
--
DROP TABLE IF EXISTS reserva;
CREATE TABLE reserva (
  id INT(11) NOT NULL AUTO_INCREMENT,
  sala_id INT(11) NOT NULL,
  periodo_id INT(11) NOT NULL,
  dia DATE NOT NULL,
  professor_desc VARCHAR(255) DEFAULT NULL,
  disciplina_desc VARCHAR(255) DEFAULT NULL,
  status INT(11) NOT NULL DEFAULT 1 COMMENT '1 reservada, 2 confirmada, 3 cancelada , 0 excluido',
  observacao TEXT DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX IDX_reserva_dia (dia),
  INDEX IDX_reserva_status (status),
  UNIQUE INDEX UK_reserva (sala_id, periodo_id, dia),
  UNIQUE INDEX UK_reserva_id (id),
  CONSTRAINT FK_reserva_periodo_id FOREIGN KEY (periodo_id)
    REFERENCES periodo(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_reserva_sala_id FOREIGN KEY (sala_id)
    REFERENCES sala(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table reserva_disciplina
--
DROP TABLE IF EXISTS reserva_disciplina;
CREATE TABLE reserva_disciplina (
  id INT(11) NOT NULL AUTO_INCREMENT,
  disciplina_id INT(11) NOT NULL,
  reserva_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_reserva_disciplina_id (id),
  CONSTRAINT FK_reserva_disciplina_disciplina_id FOREIGN KEY (disciplina_id)
    REFERENCES disciplina(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_reserva_disciplina_reserva_id FOREIGN KEY (reserva_id)
    REFERENCES reserva(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table reserva_professor
--
DROP TABLE IF EXISTS reserva_professor;
CREATE TABLE reserva_professor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  professor_id INT(11) NOT NULL,
  reserva_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_reserva_professor_id (id),
  CONSTRAINT FK_reserva_professor_professor_id FOREIGN KEY (professor_id)
    REFERENCES professor(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_reserva_professor_reserva_id FOREIGN KEY (reserva_id)
    REFERENCES reserva(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table disciplina
--

-- Table sgreserva.disciplina does not contain any data (it is empty)

-- 
-- Dumping data for table periodo
--
INSERT INTO periodo VALUES
(1, '19:40'),
(2, '21:30'),
(3, '07:40'),
(4, '10:30');

-- 
-- Dumping data for table predio
--
INSERT INTO predio VALUES
(1, 'Predio A');

-- 
-- Dumping data for table professor
--

-- Table sgreserva.professor does not contain any data (it is empty)

-- 
-- Dumping data for table usuario
--
INSERT INTO usuario VALUES
(1, 'teste', 'teste', '698dc19d489c4e4db73e28a713eab07b');

-- 
-- Dumping data for table sala
--
INSERT INTO sala VALUES
(1, 1, 'Sala 1', NULL),
(2, 1, 'Sala 2', NULL),
(3, 1, 'Sala 3', NULL),
(4, 1, 'Sala 4', NULL),
(5, 1, 'Sala 5', NULL),
(6, 1, 'Sala 6', NULL),
(7, 1, 'Sala 7', NULL),
(8, 1, 'Sala 8', NULL);

-- 
-- Dumping data for table reserva
--
INSERT INTO reserva VALUES
(1, 1, 1, '2015-10-23', 'Marco', '105645 - Fisiologia vegetal - M2', 1, NULL),
(2, 4, 3, '2015-10-23', 'Afonso T.', 'Microbiologia - Enfermagem - M6', 1, NULL),
(3, 5, 2, '2015-10-27', 'Teste', 'teste 2', 1, NULL),
(4, 2, 1, '2015-10-29', 'albertinho', 'fisica quantica', 2, 'nada.');

-- 
-- Dumping data for table reserva_disciplina
--

-- Table sgreserva.reserva_disciplina does not contain any data (it is empty)

-- 
-- Dumping data for table reserva_professor
--

-- Table sgreserva.reserva_professor does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;